# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy

    filter_sets:

        # Filtre pour affichage des photos de profil dans la rubrique "Mon compte"
        profil:
            quality: 75
            filters:
                scale:
                    dim: [ 700, 700 ]

        # Filtre pour l'affichage des photos de profil dans la rubrique des commentaires
        comment:
            quality: 75
            filters:
                scale:
                    dim: [ 100, 100 ]

        # Filtre pour l'affichage des images des publications
        picture:
            quality: 75
            filters:
                scale:
                    dim: [ 1500, 1500 ]