twig:
    # Activation du thème Bootstrap pour les formulaires
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
